name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 8, 11, 17 ]
    name: Java ${{ matrix.java }} build
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Show Maven version
        run: mvn --version
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify